version: "3.8"

services:
  mongo:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  orion:
    image: fiware/orion:3.4.0
    container_name: orion
    depends_on:
      - mongo
    ports:
      - "1026:1026"
    command: -dbhost mongo -logLevel DEBUG
    environment:
      - ORION_LOG_LEVEL=DEBUG

  iot-agent:
    image: fiware/iotagent-ul
    container_name: fiware-iot-agent
    hostname: iot-agent
    depends_on:
      - mongo
    expose:
      - "4061"
      - "7896"
    ports:
      - "4061:4061"
      - "7896:7896"
    environment:
      - IOTA_CB_HOST=orion
      - IOTA_CB_PORT=1026
      - IOTA_NORTH_PORT=4061
      - IOTA_REGISTRY_TYPE=mongodb
      - IOTA_MONGO_HOST=mongo
      - IOTA_MONGO_PORT=27017
      - IOTA_MONGO_DB=iotagent-ul
      - IOTA_HTTP_PORT=7896
      - IOTA_PROVIDER_URL=http://iot-agent:4061

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-mongodb-datasource

  snort-python:
    build: ./snort-python
    container_name: snort-python
    depends_on:
      - orion
      - iot-agent
    volumes:
      - ./snort-python/alert_json.txt:/var/log/snort/alert_json.txt

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - iot-agent

volumes:
  mongo_data:
  prometheus_data:

